### ISSUE TITLE
Version bump request

### ISSUE THREAD

**Issue by eralpsahin** [rosscooperman/marked-rails#5]
Hi,

If you are still maintaining this repository, can you release a version bump? Mainly looking to get the pipe character escape rendering fix that was added in the 0.4.0 https://github.com/markedjs/marked/releases/tag/0.4.0

**Comment by swan-amazon** [comment]
@eralpsahin , I got you... See my [pull request](https://github.com/rosscooperman/marked-rails/pull/6).

**Comment by swan-amazon** [comment]
@rosscooperman , please review and accept the pull request.
