### ISSUE TITLE
Create 9.1.2 Release and Publish to RubyGems.org

### ISSUE THREAD

**Issue by swan-amazon** [rosscooperman/marked-rails#7]
Please create 9.1.2 release and publish to RubyGems.org. Availability within RubyGems.org is necessary for my company's 3p import system. Thank you! @rosscooperman

**Comment by rosscooperman** [comment]
@swan-amazon pushed to rubygems and added a tag. Sorry for taking so long to merge that PR!

**Comment by swan-amazon** [comment]
@rosscooperman , very much appreciated, and timely. This package didn't seem particularly active, so I wasn't sure if you remembered the release process, so just a friendly nudge. Thanks!
